MODQM-189 folio-spring-base v2 update
folio-org/mod-quick-marc pull request #142
Opened 2022-01-19 11:20 UTC by ALiemeshka

2022-01-20 18:35 UTC, psmagin approved these changes

2022-01-21 07:30 UTC, Shans-Kaluhin approved these changes

2022-01-21 14:30 UTC, psmagin requested changes
Also please go through all steps in https://github.com/folio-org/folio-spring-base/blob/master/doc/release-notes.md

2022-01-21 22:16 UTC, psmagin approved these changes

2022-01-24 06:32 UTC, merged