MODQM-58 Adjust the quickMarcJson payload to provide field protection…
folio-org/mod-quick-marc pull request #143
Opened 2022-02-09 07:33 UTC by ALiemeshka

## Purpose
Since Data Import has implemented tenant-level settings for protecting MARC fields, quickMARC backend module should provide MARC record field protection status.

## Approach
add boolean property to the Item object in quickMarcJson schema
use `/field-protection-settings/marc` endpoint to get MARC field protection settings
determine field protection status and set field protection property upon parsedRecord -> quickMarcJson conversion

## Learning
[MODQM-58](https://issues.folio.org/browse/MODQM-58)

2022-02-10 10:03 UTC, psmagin requested changes

2022-02-10 10:03 UTC, psmagin commented on src/main/resources/swagger.api/schemas/fieldItem.json
> +    "protect": {
I suggest to rename it to `isProtected`

2022-02-10 10:03 UTC, psmagin commented on src/main/resources/swagger.api/schemas/fieldItem.json
> +      "example": true
Add `"readOnly": true`

2022-02-10 15:32 UTC, psmagin approved these changes

2022-02-14 10:33 UTC, viacheslavkol approved these changes

2022-02-14 11:12 UTC, Shans-Kaluhin approved these changes
Good work!

2022-02-14 12:07 UTC, merged