MODQM-228 - User able to replace the '001' field value when edit record in quickmarc
folio-org/mod-quick-marc pull request #164
Opened 2022-05-23 16:59 UTC by Igor-Gorchakov

### Purpose
_Describe the purpose of the pull request. Include background information if necessary._

### Approach
Added validation rule to check if only one 001 field is present in a record

### TODOs and Open Questions
- [ ] Use GitHub checklists. When solved, check the box and explain the answer.

### Learning
_Describe the research stage. Add links to blog posts, patterns, libraries or addons used to solve this problem._

2022-05-23 17:11 UTC, psmagin requested changes

2022-05-23 17:11 UTC, psmagin commented on src/main/java/org/folio/qm/validation/impl/common/OnlyOne100ControlFieldValidationRule.java
> +    var fieldsWith008TagCode = filterFieldsByTagCode(fieldItems, TAG_001_CONTROL_FIELD);
```suggestion
    var fieldsWith001TagCode = filterFieldsByTagCode(fieldItems, TAG_001_CONTROL_FIELD);
```

2022-05-23 17:11 UTC, psmagin commented on src/main/java/org/folio/qm/validation/impl/common/OnlyOne100ControlFieldValidationRule.java
> +    return onlyOneRequiredCondition().apply(TAG_001_CONTROL_FIELD, fieldsWith008TagCode);
Actually having a 001 tag is not required. For example, when creating new holdings record UI doesn't send a 001 tag in a request. I suggest creating a new condition that will check that there are no greater than one 001 tags existing.

2022-05-23 17:12 UTC, psmagin commented on src/main/java/org/folio/qm/validation/impl/common/OnlyOne100ControlFieldValidationRule.java
> +public class OnlyOne100ControlFieldValidationRule extends FieldValidationRule {
```suggestion
public class OnlyOne001ControlFieldValidationRule extends FieldValidationRule {
```

2022-05-24 08:09 UTC, psmagin approved these changes

2022-05-24 09:42 UTC, Shans-Kaluhin approved these changes

2022-05-24 10:30 UTC, merged