MODQM-319: Removed unneeded fields
folio-org/mod-quick-marc pull request #199
Opened 2023-03-17 08:56 UTC by hasanepam

## Purpose
_Describe the purpose of the pull request._

## Approach
_How does this change fulfill the purpose?_

### Changes checklist
- [ ] API paths, methods, request or response bodies changed, added, or removed
- [ ] Database schema changes
- [ ] Interface versions changes
- [ ] Interface dependencies added, or removed
- [ ] Permissions changed, added, or removed
- [ ] Check logging.

### TODOS and Open Questions
- [ ] Use GitHub checklists. When solved, check the box and explain the answer.

### Learning
_Describe the research stage. Add links to blog posts, patterns, libraries or addons used to solve this problem._

2023-03-22 11:42 UTC, psmagin commented on src/test/java/org/folio/qm/controller/RecordsEditorIT.java
> -      .andExpect(jsonPath("$.fields[0].authorityNaturalId").value(AUTHORITY_NATURAL_ID))
This fields still should exist in the response

2023-03-23 14:32 UTC, viacheslavkol requested changes

2023-03-23 14:32 UTC, viacheslavkol commented on src/main/java/org/folio/qm/service/impl/LinksServiceImpl.java
> +        .filter(fieldItem -> instanceLink.getAuthorityId().equals(fieldItem.getAuthorityId()))
Filtering by authorityId is present further. It'd reasonable to have 'linkId' filtering here

2023-03-29 10:51 UTC, psmagin requested changes

2023-03-29 10:51 UTC, psmagin commented on src/main/java/org/folio/qm/client/LinksClient.java
>  }
I think we do not need all these fields. You can leave only fields that are needed for implementation

2023-03-29 10:51 UTC, psmagin commented on src/main/java/org/folio/qm/converter/field/dto/BibliographicDataFieldConverter.java
> +
This logic doesn't need there as you have logic of assigning linkingRuleId in LinkService

2023-03-29 10:51 UTC, psmagin commented on src/main/resources/application.yaml
> +      - qm-fetch-linking-rules-results
I think it could be just `linking-rules-results`

2023-03-29 10:51 UTC, psmagin commented on src/test/java/org/folio/qm/controller/RecordsEditorIT.java
> +      .andExpect(jsonPath("$.fields[14].authorityNaturalId").value(AUTHORITY_NATURAL_ID));
And I think `linkingRuleId` should also be checked there

2023-03-30 07:36 UTC, psmagin commented on src/main/java/org/folio/qm/converter/field/dto/BibliographicDataFieldConverter.java
> +  private final LinksClient linksClient;
So, this is not used in a class and can be removed. As well as @RequiredArgsConstructor

2023-03-31 14:39 UTC, viacheslavkol approved these changes

2023-04-03 18:44 UTC, psmagin approved these changes

2023-04-04 08:33 UTC, psmagin approved these changes

2023-04-04 17:37 UTC, merged