MODQM-332  Implement MARC field specifications endpoint
folio-org/mod-quick-marc pull request #224
Opened 2023-08-23 09:13 UTC by pawelmol

Purpose/Overview:

UI needs information about field specifications: for now, it's only names and orders of fixed-length field items. In the scope of the story, it will be specs only for the 008 field.

Requirements/Scope:

    Implement endpoint GET /marc-specifications/<record-type>/<field-tag>
    record-type: authority/holdings/bibliographic
    The response body should have such format: [fixed-length-field-spec-example-1.json](https://issues.folio.org/secure/attachment/61148/61148_fixed-length-field-spec-example-1.json)
    Specs stored in database

Acceptance criteria:

    Covered by unit tests
    Module documentation updated
    Logging is well-defined

2023-08-28 09:53 UTC, psmagin requested changes

2023-08-28 09:53 UTC, psmagin commented on src/main/resources/db/changelog/changes/v2.6.0/field008.json
I think that it is not full spec for 008 field

2023-09-06 08:22 UTC, pawelmol commented on src/main/resources/db/changelog/changes/v2.6.0/field008.json
Good point, I have updated the specification.

2023-09-08 08:24 UTC, psmagin approved these changes

2023-09-08 08:25 UTC, psmagin commented
Please update NEWS

2023-09-08 10:55 UTC, mukhiddin-yusuf approved these changes

2023-09-08 10:57 UTC, merged